// <auto-generated />
namespace WebApplication1.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inirial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inirial1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271901591_Inirial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
