// <auto-generated />
namespace WebApplication1.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial5453334 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial5453334));
        
        string IMigrationMetadata.Id
        {
            get { return "202010010619388_initial5453334"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
